### ISSUE TITLE
make failure

### ISSUE THREAD

**Issue by orendinaimotorolasolutions** [omiksik/roam#1]
Hi 
I'm following the instructions in README.MD file to build `roam` .
After `cmake .` command I didn't get any file in `raom/build/bin` directory.
I continued to `cmake -n -j4` command and got next error:

`/usr/bin/cmake -E cmake_echo_color --switch= --green --progress-dir=/home/ubuntu/roam/build/CMakeFiles --progress-num=6 "Building CXX object roam_apps/CMakeFiles/draw_contours.dir/draw_contours.cpp.o"
cd /home/ubuntu/roam/build/roam_apps && /usr/bin/c++   -DWITH_OPENMP -I/home/ubuntu/roam/build/roam_apps -I/home/ubuntu/roam/roam_apps -isystem /usr/local/include -isystem /usr/local/include/opencv  -fopenmp   -std=gnu++14 -o CMakeFiles/draw_contours.dir/draw_contours.cpp.o -c /home/ubuntu/roam/roam_apps/draw_contours.cpp
make[2]: *** No rule to make target 'roam/libroam_lib.a', needed by 'bin/roam_cli'.  Stop.
/usr/bin/cmake -E cmake_echo_color --switch= --green --progress-dir=/home/ubuntu/roam/build/CMakeFiles --progress-num=7 "Building CXX object roam_apps/CMakeFiles/draw_contours.dir/main_utils.cpp.o"
cd /home/ubuntu/roam/build/roam_apps && /usr/bin/c++   -DWITH_OPENMP -I/home/ubuntu/roam/build/roam_apps -I/home/ubuntu/roam/roam_apps -isystem /usr/local/include -isystem /usr/local/include/opencv  -fopenmp   -std=gnu++14 -o CMakeFiles/draw_contours.dir/main_utils.cpp.o -c /home/ubuntu/roam/roam_apps/main_utils.cpp
make[2]: *** No rule to make target 'roam/libroam_lib.a', needed by 'bin/draw_contours'.  Stop.
CMakeFiles/Makefile2:151: recipe for target 'roam_apps/CMakeFiles/roam_cli.dir/all' failed
make[1]: *** [roam_apps/CMakeFiles/roam_cli.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:191: recipe for target 'roam_apps/CMakeFiles/draw_contours.dir/all' failed
make[1]: *** [roam_apps/CMakeFiles/draw_contours.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

notice the `No rule to make target 'roam/libroam_lib.a', needed by 'bin/roam_cli` error. 
Do you have any solution regarding this?

Thanks

**Comment by omiksik** [comment]
Hi, 

No, you will not get anything in `roam/build/bin` after `cmake ..`

1) `cd roam/build`
2) `cmake ..`
3) `make -j4`

Now, you can navigate to `roam/build/bin` where you will find the compiled code...
