### ISSUE TITLE
model.yml.gz ?

### ISSUE THREAD

**Issue by lulu1315** [omiksik/roam#2]
hello
thanks for the code!
looking at default.yaml I see a reference to this file
grad_model_name_trained_detector: "/home/juan-manuel/bin/model.yml.gz"
do I need it ?.where can I get it ?
thanks in advance
luc

**Comment by jperezrua** [comment]
Hey there @lulu1315, you shouldn't need this file, as we did not find useful to use "smart" edge detectors.

**Comment by juanmanpr** [comment]
closed #2

**Comment by omiksik** [comment]
what about this guy?

https://github.com/omiksik/roam/issues/1

didn't he just forgot to go into the actual directory?

2018-07-11 14:30 GMT+01:00 Juan Manuel <notifications@github.com>:

**Comment by lulu1315** [comment]
thank you!
