### ISSUE TITLE
roam_cli: /root/roam/roam/src/SnapcutTerms.cpp:319: virtual FLOAT_TYPE SnapcutPairwiseImpl_temporalGMM::GetCost(const Point&, const Point&): Assertion `this->edge_initialized' failed. Aborted

### ISSUE THREAD

**Issue by blackmad** [omiksik/roam#3]
Have you ever seen this error?

roam_cli: /root/roam/roam/src/SnapcutTerms.cpp:319: virtual FLOAT_TYPE SnapcutPairwiseImpl_temporalGMM::GetCost(const Point&, const Point&): Assertion `this->edge_initialized' failed.
Aborted

It happens when I try to make my own masks.

This is what my mask looks like - it's all b&w, grayscale png, but consistently gives that error
![90](https://user-images.githubusercontent.com/445616/45582078-cb865e80-b877-11e8-854d-defbd6cede90.png)

this random mask from the DAVIS set works fine even though it's completely different from the size of the input images I'm trying to feed roam 
![mask2](https://user-images.githubusercontent.com/445616/45582091-f375c200-b877-11e8-8505-0da111aeea15.png)

**Comment by jperezrua** [comment]
Hey @blackmad, thanks for reporting this. It is clearly a bug from our side. A simple non-perfect workaround for you would be to use the "win" argument to zero-pad the image. I think our Snapcut model is trying to initialize a GMM from the contours at the border at finds that the are no pixels in there.

Use for example:
--win=20

**Comment by blackmad** [comment]
awesome, that worked
